AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-07761f3ae34c4478d
      InstanceType: t2.micro
      KeyName: sshkey
      SubnetId: subnet-06ab1a78c1c9f046e
      SecurityGroupIds:
        - sg-08bb9330aef3bfaa5

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: "/"
      HealthCheckProtocol: "HTTP"
      HealthCheckPort: 80
      Port: 80
      Protocol: "HTTP"
      Targets:
        - Id: !Ref MyEC2Instance
          Port: 80
      VpcId: vpc-03aa50dce6fc9537a # Replace with your existing VPC ID

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyLoadBalancer
      Subnets:
        - subnet-06ab1a78c1c9f046e # Subnet in Availability Zone A
        - subnet-09c7e352b133ba384 # Subnet in Availability Zone B
        - subnet-0ec8307bd7a734c57 # Subnet in Availability Zone C
      SecurityGroups:
        - sg-08bb9330aef3bfaa5
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "60"
      Tags:
        - Key: Name
          Value: MyLoadBalancer
      IpAddressType: ipv4

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: HTTP

  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-07761f3ae34c4478d
      InstanceType: t2.micro
      SecurityGroups:
        - sg-08bb9330aef3bfaa5
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo systemctl enable httpd
          sudo systemctl start httpd
          sudo echo '<html><body><h1>Hello, World!</h1></body></html>' > /var/www/html/index.html
          # Additional setup and configurations here

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: MyAutoScalingGroup
      VPCZoneIdentifier:
        - subnet-06ab1a78c1c9f046e # Replace with your existing Subnet ID
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        - !Ref MyTargetGroup